ControleDeContatos/Controllers/ContatoController.cs
using ControleDeContatos.Filters;
using ControleDeContatos.Helper;
using ControleDeContatos.Models;
using ControleDeContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace ControleDeContatos.Controllers
{
    [PaginaParaUsuarioLogado]
    public class ContatoController : Controller
    {
        private readonly IContatoRepositorio _contatoRepositorio;
        private readonly ISessao _sessao;

        public ContatoController(IContatoRepositorio contatoRepositorio, ISessao sessao)
        {
            _contatoRepositorio = contatoRepositorio;
            _sessao = sessao;
        }

        public IActionResult Index()
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
            List<ContatoModel> contatos = _contatoRepositorio.BuscarTodos(usuarioLogado.Id);

            return View(contatos);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {

           ContatoModel contato = _contatoRepositorio.ListarPorId(id);

            return View(contato);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListarPorId(id);

            return View(contato);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _contatoRepositorio.Apagar(id);

               if (apagado)
                {
                    TempData["MensagemSucesso"] = "Contato apagado com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = $"Não foi possível apagar o contato.";
                }
                
                return RedirectToAction("Index");
            }
            catch (SystemException erro)
            {
                TempData["MensagemErro"] = $"Não foi possível apagar o contato. Detalhes do erro: {erro.Message}";
                return RedirectToAction("Index");
            }

        }

        [HttpPost]
        public IActionResult Criar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                    contato.UsuarioId = usuarioLogado.Id;

                    contato = _contatoRepositorio.Adicionar(contato);

                    TempData["MensagemSucesso"] = "Contato cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }

                    return View(contato);
            }
            catch (SystemException erro)
            {
                    TempData["MensagemErro"] = $"Não foi possível cadastrar o contato. Detalhes do erro: {erro.Message}";
                    return RedirectToAction("Index");
            }
            
        }

        [HttpPost]
        public IActionResult Alterar(ContatoModel contato)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                    contato.UsuarioId = usuarioLogado.Id;

                    contato = _contatoRepositorio.Atualizar(contato);
                    TempData["MensagemSucesso"] = "Contato alterado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View("Editar", contato);
            }
            catch (SystemException erro)
            {
                TempData["MensagemErro"] = $"Não foi possível alterar o contato. Detalhes do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

    }
}

ControleDeContatos/Views/Contato/ApagarConfirmacao.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Confirmação apagar o contato";
}

<div class="text-center">

    <h3>Realmente deseja apagar o contato (@Model.Nome)?</h3>

</div>

<a class="btn btn-primary w-100 mb-1" asp-controller="Contato" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger w-100" asp-controller="Contato" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar exclusão</a>

ControleDeContatos/Views/Contato/Criar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Criar contato";
}

<div class="text-center">

	<h1 class="display-4">Cadastrar contato</h1>

</div>

    <form asp-controller="Contato" asp-action="Criar" method="post">

        <div class="form-group mb-3">
            <label for="nome">Nome</label>
            <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome">
            @Html.ValidationMessageFor(x => x.Nome)
        </div>

         <div class="form-group mb-3">
            <label for="email">E-mail</label>
            <input type="text" asp-for="Email" class="form-control" placeholder="Digite o e-mail">
        @Html.ValidationMessageFor(x => x.Email)
        </div>

         <div class="form-group">
            <label for="celular">Celular</label>
            <input type="text" asp-for="Celular" class="form-control" placeholder="Digite o celular">
        @Html.ValidationMessageFor(x => x.Celular)
        </div>

        <div class="mt-3">
            <button type="submit" class="btn btn-primary w-100 mb-2">Adicionar</button>
        <a class="btn btn-secondary w-100" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
        </div>

    </form>

ControleDeContatos/Views/Contato/Editar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Editar contato";
}

<div class="text-center">

    <h1 class="display-4">Editar contato</h1>

</div>

<form asp-controller="Contato" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="Id"/>

    <div class="form-group mb-3">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group mb-3">
        <label for="email">E-mail</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Digite o e-mail">
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <div class="form-group">
        <label for="celular">Celular</label>
        <input type="text" asp-for="Celular" class="form-control" placeholder="Digite o celular">
        @Html.ValidationMessageFor(x => x.Celular)
    </div>

    <div class="mt-3">
        <button type="submit" class="btn btn-primary w-100 mb-2">Alterar</button>
        <a class="btn btn-secondary w-100" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
    </div>

</form>

ControleDeContatos/Views/Contato/Index.cshtml
@model List<ContatoModel>
@{
    ViewData["Title"] = "Listagem de contatos";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">

        <a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Criar" >Adicionar novo contato</a>

    </div>

    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    } 

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }


    <h1 class="display-4">Listagem de Contatos</h1>

    <table class="table" id="table-contatos">
        <thead>
            <tr>
                <th scope="col" class="text-center">#</th>
                <th scope="col" class="text-center">Nome</th>
                <th scope="col" class="text-center">E-mail</th>
                <th scope="col" class="text-center">Celular</th>
                <th scope="col" class="text-center"></th>
            </tr> 
        </thead>
        <tbody>
            
            @if(Model != null && Model.Any())
            {
                foreach (ContatoModel contato in Model)
                {
                    <tr>
                        <th scope="row">@contato.Id</th>
                        <td>@contato.Nome</td>
                        <td>@contato.Email</td>
                        <td>@contato.Celular</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a role="button" class="btn btn-primary" asp-route-id="@contato.Id" asp-controller="Contato" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@contato.Id" asp-controller="Contato" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="5">Nenhum contato encontrado</td></tr>
            }

        </tbody>
    </table>
</div>